package cl.tiempojusto.statemachine.online;
public enum OnlineState { WINNER_SELECTED, JOIN_WINDOW, FREE_ONLINE, AWAITING_PAID_CONFIRMATION, PAID_ACTIVE, RECONNECTING, FINISHED_FREE, FINISHED_RECONNECT_TIMEOUT, FINISHED }
